// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: api/zoo.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Пол и тип животных
type Gender int32

const (
	Gender_MAN   Gender = 0
	Gender_WOMEN Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MAN",
		1: "WOMEN",
	}
	Gender_value = map[string]int32{
		"MAN":   0,
		"WOMEN": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zoo_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_api_zoo_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{0}
}

type Species int32

const (
	Species_CAT Species = 0
	Species_DOG Species = 1
	Species_RAT Species = 2
)

// Enum value maps for Species.
var (
	Species_name = map[int32]string{
		0: "CAT",
		1: "DOG",
		2: "RAT",
	}
	Species_value = map[string]int32{
		"CAT": 0,
		"DOG": 1,
		"RAT": 2,
	}
)

func (x Species) Enum() *Species {
	p := new(Species)
	*p = x
	return p
}

func (x Species) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Species) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zoo_proto_enumTypes[1].Descriptor()
}

func (Species) Type() protoreflect.EnumType {
	return &file_api_zoo_proto_enumTypes[1]
}

func (x Species) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Species.Descriptor instead.
func (Species) EnumDescriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{1}
}

// Структура животного
type AnimalType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Age         int32   `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	RainbowSex  Gender  `protobuf:"varint,5,opt,name=rainbowSex,proto3,enum=main.Gender" json:"rainbowSex,omitempty"`
	Type        Species `protobuf:"varint,6,opt,name=type,proto3,enum=main.Species" json:"type,omitempty"`
}

func (x *AnimalType) Reset() {
	*x = AnimalType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalType) ProtoMessage() {}

func (x *AnimalType) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalType.ProtoReflect.Descriptor instead.
func (*AnimalType) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{0}
}

func (x *AnimalType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimalType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnimalType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnimalType) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AnimalType) GetRainbowSex() Gender {
	if x != nil {
		return x.RainbowSex
	}
	return Gender_MAN
}

func (x *AnimalType) GetType() Species {
	if x != nil {
		return x.Type
	}
	return Species_CAT
}

type AnimalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimalType *AnimalType `protobuf:"bytes,1,opt,name=animalType,proto3" json:"animalType,omitempty"`
}

func (x *AnimalResponse) Reset() {
	*x = AnimalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalResponse) ProtoMessage() {}

func (x *AnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalResponse.ProtoReflect.Descriptor instead.
func (*AnimalResponse) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{1}
}

func (x *AnimalResponse) GetAnimalType() *AnimalType {
	if x != nil {
		return x.AnimalType
	}
	return nil
}

type AnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AnimalRequest) Reset() {
	*x = AnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalRequest) ProtoMessage() {}

func (x *AnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalRequest.ProtoReflect.Descriptor instead.
func (*AnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{2}
}

func (x *AnimalRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AnimalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of disks.
	Animal []*AnimalResponse `protobuf:"bytes,1,rep,name=Animal,proto3" json:"Animal,omitempty"`
	// Token of the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *AnimalsResponse) Reset() {
	*x = AnimalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalsResponse) ProtoMessage() {}

func (x *AnimalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalsResponse.ProtoReflect.Descriptor instead.
func (*AnimalsResponse) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{3}
}

func (x *AnimalsResponse) GetAnimal() []*AnimalResponse {
	if x != nil {
		return x.Animal
	}
	return nil
}

func (x *AnimalsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PaginateAnimals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum number of results per page.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token of the requested result page.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *PaginateAnimals) Reset() {
	*x = PaginateAnimals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginateAnimals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateAnimals) ProtoMessage() {}

func (x *PaginateAnimals) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateAnimals.ProtoReflect.Descriptor instead.
func (*PaginateAnimals) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{4}
}

func (x *PaginateAnimals) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginateAnimals) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAnimalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginateAnimals *PaginateAnimals `protobuf:"bytes,1,opt,name=paginateAnimals,proto3" json:"paginateAnimals,omitempty"`
}

func (x *ListAnimalsRequest) Reset() {
	*x = ListAnimalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_zoo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnimalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnimalsRequest) ProtoMessage() {}

func (x *ListAnimalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zoo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnimalsRequest.ProtoReflect.Descriptor instead.
func (*ListAnimalsRequest) Descriptor() ([]byte, []int) {
	return file_api_zoo_proto_rawDescGZIP(), []int{5}
}

func (x *ListAnimalsRequest) GetPaginateAnimals() *PaginateAnimals {
	if x != nil {
		return x.PaginateAnimals
	}
	return nil
}

var File_api_zoo_proto protoreflect.FileDescriptor

var file_api_zoo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x7a, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xb5, 0x01, 0x0a, 0x0a, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x0a,
	0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x53, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x0a,
	0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x53, 0x65, 0x78, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x42, 0x0a,
	0x0e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x67, 0x0a, 0x0f, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65,
	0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4d, 0x0a, 0x0f, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x55, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3f, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x52, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x73, 0x2a, 0x1c, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x41, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x4f, 0x4d, 0x45, 0x4e, 0x10, 0x01, 0x2a,
	0x24, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41,
	0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4f, 0x47, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x52, 0x41, 0x54, 0x10, 0x02, 0x32, 0x80, 0x01, 0x0a, 0x0d, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_zoo_proto_rawDescOnce sync.Once
	file_api_zoo_proto_rawDescData = file_api_zoo_proto_rawDesc
)

func file_api_zoo_proto_rawDescGZIP() []byte {
	file_api_zoo_proto_rawDescOnce.Do(func() {
		file_api_zoo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_zoo_proto_rawDescData)
	})
	return file_api_zoo_proto_rawDescData
}

var file_api_zoo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_zoo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_zoo_proto_goTypes = []interface{}{
	(Gender)(0),                // 0: main.Gender
	(Species)(0),               // 1: main.Species
	(*AnimalType)(nil),         // 2: main.AnimalType
	(*AnimalResponse)(nil),     // 3: main.AnimalResponse
	(*AnimalRequest)(nil),      // 4: main.AnimalRequest
	(*AnimalsResponse)(nil),    // 5: main.AnimalsResponse
	(*PaginateAnimals)(nil),    // 6: main.PaginateAnimals
	(*ListAnimalsRequest)(nil), // 7: main.ListAnimalsRequest
}
var file_api_zoo_proto_depIdxs = []int32{
	0, // 0: main.AnimalType.rainbowSex:type_name -> main.Gender
	1, // 1: main.AnimalType.type:type_name -> main.Species
	2, // 2: main.AnimalResponse.animalType:type_name -> main.AnimalType
	3, // 3: main.AnimalsResponse.Animal:type_name -> main.AnimalResponse
	6, // 4: main.ListAnimalsRequest.paginateAnimals:type_name -> main.PaginateAnimals
	4, // 5: main.AnimalService.GetAnimal:input_type -> main.AnimalRequest
	7, // 6: main.AnimalService.List:input_type -> main.ListAnimalsRequest
	3, // 7: main.AnimalService.GetAnimal:output_type -> main.AnimalResponse
	5, // 8: main.AnimalService.List:output_type -> main.AnimalsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_zoo_proto_init() }
func file_api_zoo_proto_init() {
	if File_api_zoo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_zoo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_zoo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_zoo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_zoo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_zoo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginateAnimals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_zoo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnimalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_zoo_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zoo_proto_goTypes,
		DependencyIndexes: file_api_zoo_proto_depIdxs,
		EnumInfos:         file_api_zoo_proto_enumTypes,
		MessageInfos:      file_api_zoo_proto_msgTypes,
	}.Build()
	File_api_zoo_proto = out.File
	file_api_zoo_proto_rawDesc = nil
	file_api_zoo_proto_goTypes = nil
	file_api_zoo_proto_depIdxs = nil
}
